### ISSUE TITLE
Request for a working demo

### ISSUE THREAD

**Issue by nueverest** [aws/amazon-cognito-identity-js#150] opened 2016-09-20 23:26 UTC
I would like to see a working demo preferably that implements the use cases outlined in the readme. 

The more plug and play this is the faster I can get things done.

**Comment by itrestian** [comment] 2016-09-21 04:34
As a company, we don't usually comment on the future direction of products and features, but developer experience is definitely something we are taking into account. As such we are considering to enhance developer experience by coming out with fully working tutorials. However, we cannot comment on any timelines for when this is going to become available.

**Comment by vinodhum** [comment] 2016-09-22 01:04
+1 on this, been trying for almost week and still cant get cognito work with AWS sdk. (went through all the documents and fallowed exact same examples)
cognito is very confusing and it would be great if we can have working example.

**Comment by simonbuchan** [comment] 2016-09-22 04:38
Part of the issue is that useful examples need a fair amount of AWS resources to exist, which is somewhat tricky to get right when you're learning.

Perhaps an `npm init`-ish script that can help select or create the resources for you and save to a `user-config.json` (git-ignored)?

**Comment by nueverest** [comment] 2016-09-27 14:14
@vinodhum  Check this out https://github.com/emmanuelmillionaer/aws-cognito-js-login 

It is not the most amazing example, but it helped me to get started.

**Comment by pchaganti** [comment] 2016-10-25 22:54
👍

**Comment by vbudilov** [comment] 2016-12-23 06:47
@nueverest , 

Here's a working demo: https://github.com/awslabs/aws-cognito-angular2-quickstart

**Comment by prem911** [comment] 2016-12-30 12:35
Looking for a complete nodejs tutorial. I have reached to a stage where I can create a cognito user, make the confirm registration call but beyond that struggling in signin with the credentials.
Getting "ReferenceError: navigator is not defined"

**Comment by itrestian** [comment] 2017-02-08 14:31
Closing as examples were provided and node js issue was solved in

https://github.com/aws/amazon-cognito-identity-js/issues/231

**Closed as completed by itrestian** 2017-02-08 14:31 UTC
Labels: question
