### ISSUE TITLE
Cannot read property 'NewDeviceMetadata' of undefined

### ISSUE THREAD

**Issue by vipermn** [aws/amazon-cognito-identity-js#132] opened 2016-08-27 00:56 UTC
aws-cognito-sdk.min.js:20 Uncaught TypeError: Cannot read property 'NewDeviceMetadata' of undefined

Seems to fail right after the verifying the MFA, because it doesn't hit the onSuccess: branch of cognitoUser.authenticateUser method.

I am getting this every time I try to login.  The js code previously worked fine.  Now I am seeing this error everytime.   This is a web application (Angularjs 1.x).

Seeing the updated code in github, I pulled the latest (today's) two min files in the dist directory.  Also bumped up the sdk to https://sdk.amazonaws.com/js/aws-sdk-2.5.3.min.js .  No change.  

Login worked fine previously.  Login from the sample Android app still continues to works fine.

This is going against UserPools in the us-west-2 region.

**Comment by itrestian** [comment] 2016-08-28 04:21
Thanks for bringing this up. The changes shouldn't have affected that behavior. I'll look into it asap.

**Comment by itrestian** [comment] 2016-08-31 23:33
This strangely works for me. Basically a user pool with MFA enabled. Can you send me the code snippet that is failing the authentication. 

And what is the app configuration, is device tracking enabled? Also can you send me the request / responses from the service (want to see if you are getting tokens in the first place and what is failing authentication based on the reply).

**Comment by vipermn** [comment] 2016-09-01 16:02
Ionut, as part of my testing that night I tried both Firefox and Chrome.  I was able to connect in with FireFox the first two times, after that it failed.  I reached a point with Chrome where it failed every time.  Basically, in Chrome, I create a new Incognito window, go to my page (being served from my local webserver) and try the login process.  It always popped asking for the verification code, then would fail with the error.  

I do have device tracking turned on.  One user I was testing had 19 different devices registered, another had 8.  

I came back the next day, after creating this issue, and I loaded the latest from the AWS JS SDK by importing the library into my eclipse project (i.e. not using CDN).  Then it always worked.  Same web app code, same user pool, same user.  I don't know if it was something flaky with AWS that night or what.  I just looked at the version in the AWS JS SDK min file and it shows 2.5.1.  When I was having the issues I was using 2.5.3 and 2.5.2 from the CDN.

For additional testing today, I just changed my html page to reference the  AWS JS SDK 2.5.2 CDN, then the 2.5.3 CDN, and they both work today.  

FWIW, I am able to recreate the error every time by logging in successfully (get token), logging out, then logging in again (all in the same window).  I don't know if that would be an expected error when logging in again from the same window.  The error:  
aws-cognito-sdk.min.js;jsessionid=6024C437A0D9852D3C9836088C589FA0:20 Uncaught TypeError: Cannot read property 'NewDeviceMetadata' of undefined

Pretty standard code sample as shown in the aws docs.  Here is the specific code snippet that is failing, It fails on the onSuccess because there is no success:
        self.cognitoUser.authenticateUser(authenticationDetails, {
            onSuccess: function (result) {
                console.log('access token + ' + result.getAccessToken().getJwtToken());
                self.accessToken = result.getAccessToken().getJwtToken();
                console.log('id token + ' + result.getIdToken().getJwtToken());
                self.idToken = result.getIdToken().getJwtToken();

As noted earlier, the mfaRequired: part of the authenticateUser method was always working.  

I hope this helps.   Let me know if you need more.
- T

**Comment by dthuering** [comment] 2016-10-10 16:02
I got the same error when I tried to log in with a user I created myself in the backend. He needed to change the password on the first login, but the callback was not called.
Then I added a user through the SDK, confirmed it in the backend and could log in without getting the error.

**Comment by Zingoer** [comment] 2016-10-13 14:24
It happens recently for me as well. What I've done as following:

1. Create a user in Cognito (which is a new feature in this month I think, originally I use import user and everything works fine)
2. Enter Username, check Send an invitation to this new user with SMS, Enter Temp password, Phone number and Email, but **uncheck** Mark 'phone number as verified' and 'Mark email as verified'
3. User is created with FORCE_CHANGE_PASSWORD Status
4. I received a SMS with username and temp password
5. I enter them into my angular 1.x webapp and try to login and fail with the error 'Uncaught TypeError: Cannot read property 'NewDeviceMetadata' of undefined'. The user status is still FORCE_CHANGE_PASSWORD. However, this error doesn't hit onFailure in method authenticateUser. Therefore, I'm not sure how I can redirect user to reset password

**Comment by l3wi** [comment] 2016-10-18 23:29
I'm having the same issue as @biohazardffm. I'm trying the new Password Challenge but I'm getting : 
`Uncaught TypeError: Cannot read property 'NewDeviceMetadata' of undefined`

**Comment by itrestian** [comment] 2016-10-20 00:57
Could you guys share the code you are running and some recent request IDs. For the new password challenge, in case of a successful call, it should either trigger MFA, issue tokens, or throw an exception. For the error you are getting, it would mean there's no exception, tokens haven't been issued and MFA wasn't triggered.

**Comment by itrestian** [comment] 2016-10-21 22:27
Could you try guys to reproduce with the latest code. This occurred when devices tracking is always enabled and we don't use the remembered device to bypass MFA, a condition was missing.

**Comment by mlackman** [comment] 2016-10-22 17:18
I had the same issue. With the latest code everything worked ok.

**Comment by itrestian** [comment] 2016-10-22 20:42
Thanks. Closing this. Feel free to reopen if it still occurs.

**Closed as completed by itrestian** 2016-10-22 20:42 UTC

**Comment by pbowyer** [comment] 2017-03-30 12:33
Weirdly, this error has just started happening today for us. Yesterday, fine. Today, no code changes, no new deployment - but this error. Different line number to the above.
