### ISSUE TITLE
Resetting password model doesn't appear to work

### ISSUE THREAD

**Issue by npalethorpe** [aws/amazon-cognito-identity-js#98] opened 2016-08-04 19:54 UTC
I seem to be unable to get the Reset Password procedure to work.

I use the authenticate function using an account which I have marked as '**Reset Password**' within the User Pools web console which causes the `cognitoUser.authenticateUser` to throw a `onFailure` callback with the `PasswordResetRequiredException` exception. 

I then navigate the user to a reset password screen, where I enter my existing password and a new password and make a `cognitoUser.changePassword` call. This call then returns a `User is not authenticated` error.

I thought I was maybe reinitialising the `cognitoUser` object somewhere, however I copied the reset password code directly into the `onFailure` callback of the `cognitoUser.authenticateUser` function and it still returns the same `User is not authenticated` error.

Am I doing something wrong?

**Comment by itrestian** [comment] 2016-08-04 20:46
Are you calling forgotPassword or changePassword? forgotPassword doesn't require an access token while changePassword requires one.

**Comment by itrestian** [comment] 2016-08-04 20:59
You should make a forgotPassword call. changePassword is an authenticated call.

**Comment by npalethorpe** [comment] 2016-08-05 00:08
Thanks for that. It has semi-sorted my problems out.

I carry out the Forgotten Password route, receive the code, insert that and my new password and the `onSuccess` function gets called (I'm presuming this call isn't supposed to return a value because I'm just get an `undefined` back with the `onSuccess`?) and all looks fine. 
However when I go to then sign in using my username and new password the `cognitoUser.authenticateUser` is still returning a `PasswordResetRequiredException`.

What's even weirder is that I can still enter my old password and any other random string password alongside my correct username and this also returns an `onFailure` exception of `PasswordResetRequiredException`. If I enter a different (but invalid) username I get the correct response of `ResourceNotFoundException`.

It's almost as though my username and the original password for that username has been cached somewhere!?

Appreciate the help!

**Comment by npalethorpe** [comment] 2016-08-06 17:19
I've done more looking into this...

I kept getting the `PasswordResetRequiredException` each time I authenticated (no matter what password I was entering - incorrect or not), I noticed in the User Pools section of the AWS web console that my user had the `Confirm` button showing, so I clicked this and suddenly incorrect passwords for my user started coming through as `NotAuthorizedException` and the last password I had updated to using the forgotten password procedure has taken affect - which is all correct! 

So the questions really are:
1. Why does clicking the `Reset Password` button in the User Pools section of the AWS web portal set my account to unconfirmed.
2. Why was it sending me a `PasswordResetRequiredException` exception during Authentication whilst the account was in this state no matter what password had been entered and regardless of whether a successful password reset had just occurred.

Entering a wrong password should always return the `NotAuthorizedException` and if the AWS Userpool 'unconfirmed' is different from the confirmed status that the user must complete through a sign up process then shouldn't there be another type of exception thrown in this scenario?

**Comment by chetanme** [comment] 2016-08-07 01:15
You just ran into a bug on our web console. When you click Reset Password on the console, which calls AdminResetPassword API behind the scenes, it changes the user state to `RESET_REQUIRED` from `CONFIRMED` (not `UNCONFIRMED`). This invalidates the current user password, while ForgotPassword call doesn't. It is only the console that is currently not showing the correct user state and we are working on fixing it.

Since the user was in `RESET_REQUIRED` state you were getting `PasswordResetRequiredException`. Hope this clarifies things.

**Comment by itrestian** [comment] 2016-08-18 21:44
This should be fixed now.

**Closed as completed by itrestian** 2016-08-18 21:44 UTC
