### ISSUE TITLE
Password Strength returns one error only

### ISSUE THREAD

**Issue by bradennapier** [aws/amazon-cognito-identity-js#414] opened 2017-05-26 00:32 UTC
In the case your password validation is not met, it only throws one error right now rather than all errors.  For example, if the user needs to have number, symbol, and upper case and has

'password'

you only get a single error reported rather than each one in an array or similar.  It would be preferable to have all errors reported either in an array or as extra arguments to the onFailed callback so that the user can be informed of ALL mistakes they have made

**Comment by kushwahavinay** [comment] 2017-06-01 07:32
This is known issue and we have it in our backlog to fix it. Meanwhile, is it possible for you to add the client side check for password policy for better error messaging?

**Comment by itrestian** [comment] 2017-06-14 21:37
Closing this as a duplicate of https://github.com/aws/amazon-cognito-identity-js/issues/311

**Closed as completed by itrestian** 2017-06-14 21:37 UTC
