### ISSUE TITLE
Unable to verify via email link

### ISSUE THREAD

**Issue by GarlandM** [aws/amazon-cognito-identity-js#604] opened 2017-11-21 11:07 UTC
Hi All,

Up until yesterday, this worked without issue. 

**My signup flow:**

Website signup -> sent verification email -> verify via link

However any time someone signs up now they're still the sent the link correctly, but anytime they click on the link it'll come back with: **An error was encountered with the requested page.** and the error is: **invalid_request**

**Comment by jndev90** [comment] 2017-11-21 12:26
Same issue here.

**Comment by tobiastornros** [comment] 2017-11-21 12:49
Same here, link is sent to user but doesn´t work.

**Comment by itrestian** [comment] 2017-11-21 17:44
What region are your pools in?

**Comment by GarlandM** [comment] 2017-11-21 17:46
US-East for me.

**Comment by itrestian** [comment] 2017-11-21 18:09
We are not able to reproduce this issue. Can you email me (trestian@amazon.com) the pool ID and some request information (like a request id and some timing information of when the request was made).

**Comment by jndev90** [comment] 2017-11-21 18:27
EU-central1, tested with multiple pool ids.

**Comment by GarlandM** [comment] 2017-11-21 18:30
@itrestian

I've emailed you.

**Comment by itrestian** [comment] 2017-11-21 18:31
Thanks, we're looking into it.

**Comment by rachitdhall** [comment] 2017-11-21 18:56
We have been able to reproduce the issue. It happens when you do not have any OAuth Flows/Scopes configured. This is a recent bug and we are working on a fix.

A workaround is to enable any OAuth flow which will allow it to work.

**Comment by rachitdhall** [comment] 2017-11-22 09:33
The fix has been deployed to all regions, please let us know if you are still having issues. Thanks for your patience.

**Closed as completed by rachitdhall** 2017-11-22 09:33 UTC

**Comment by jndev90** [comment] 2017-11-22 11:14
I can confirm that the issue is resolved.
