### ISSUE TITLE
Receiving a UserNotConfirmedException on authenticate when authentication is incorrect

### ISSUE THREAD

**Issue by npalethorpe** [aws/amazon-cognito-identity-js#288] opened 2017-02-12 17:37 UTC
I've realised that I don't have to type a correct password/username combination for an unverified account to receive back a 'UserNotConfirmedException' response from a call to 'authenticateUser'.

If the user types in a correct username and incorrect password I would expect to get an 'NotAuthorizedException' response regardless of the current account state.

Steps to replicate:
1. Sign up for an account using the 'signUp' function on the user pool
2. Receive an email confirmation code
3. Attempt to log in to the newly created (un-verified) account using the correct username but wrong password.
4. You will receive a response code of 'UserNotConfirmedException'.

My question is - is this correct - is this the model you were aiming for or a bug in the process? The reason I feel it is incorrect is because this will allow anyone to call a 'resendConfirmationCode' for someone else's unverified account - I appreciate the code will only ever go to the owners email however this could be seen as us spamming that owner.

Thanks for any feedback.

**Comment by rachitdhall** [comment] 2017-02-13 01:19
Yes, this is the intended behavior. We received feedback from the developers that if the user is not confirmed they do not want NotAuthorizedException so that they can correctly take the next step to redirect user to the confirmation flow. The code always goes to the correct owner so it will not be leaked also.

Closing, feel free to re-open if need be.

**Closed as completed by rachitdhall** 2017-02-13 01:19 UTC
