### ISSUE TITLE
Plus Sign (+) not a Special Character

### ISSUE THREAD

**Issue by paolavness** [aws/amazon-cognito-identity-js#556] opened 2017-10-17 16:16 UTC
Hi there,
I've noticed the `+` is not a special character and am wondering what the reason for this is and whether it can be added as one. A small number of users appear to use `+` as their default "special character" across their passwords. We've had complaints from them about not being able to use it in our app

Thank you,
Paola

**Comment by itrestian** [comment] 2017-11-01 23:47
Closing as a duplicate of: https://github.com/aws/amazon-cognito-identity-js/issues/527

**Closed as completed by itrestian** 2017-11-01 23:47 UTC
