### ISSUE TITLE
Username and pool information are required with error with confirmRegistration

### ISSUE THREAD

**Issue by nnurmano** [aws/amazon-cognito-identity-js#537] opened 2017-09-22 16:47 UTC
I would like to confirm user with a verification code. The user pool is configured with username and
"Also allow sign in with verified email address", I use the following piece of code
```
               const userData = {
			Username: email,
			Pool: userPool
		}
		// create the `cognitoUser` object
		const cognitoUser = new CognitoUser(userData);
		console.log('userdata', userData);
		// call the `confirmRegistration()` function of `cognitoUser` and pass in the verification PIN
		cognitoUser.confirmRegistration(verificationCode, true, function (error, result) {
			if (error) {
				console.log('error', error);
				failure(error)
				return;
			}
```
But when I click on verify button and pass email to the username field "Username/client id combination not found" is thrown. The same code works if I pass username instead of email. Why is this happening here?

**Comment by itrestian** [comment] 2017-09-22 18:57
confirmRegistration is not compatible with alias. Closing as duplicate of:

https://github.com/aws/amazon-cognito-identity-js/issues/277

**Closed as completed by itrestian** 2017-09-22 18:57 UTC
