### ISSUE TITLE
1.16.0 - CognitoUser.authenticateUser is immediately crashing Chrome Tab

### ISSUE THREAD

**Issue by pizzarob** [aws/amazon-cognito-identity-js#315] opened 2017-03-03 21:55 UTC
Chrome Version: 56.0.2924.87 (64-bit)
OSX Version: 10.12.3 (16D32)
amazon-cognito-identity-js Package Version: 1.16.0

When I call CognitoUser.authenticateUser the chrome browser tab immediately goes to the Aww Snap page. Reverting to version 1.15.0 fixes the issue. 

![image](https://cloud.githubusercontent.com/assets/5282495/23570436/f7c731b8-0018-11e7-8cb1-8458edae8276.png)

**Comment by itrestian** [comment] 2017-03-03 22:35
Version 1.16 pulled jsbn into our code base so that dependency is no longer required. It might be the case that there are conflicts if you don't remove that?

**Comment by jogold** [comment] 2017-03-03 22:42
I'm experiencing the same issue with 1.16.0 on Windows 7. Downgrading to 1.15.0 also fixes the issue.

It only happens in my development environment not in production, using react-boilerplate (https://github.com/react-boilerplate/react-boilerplate).

**Comment by ghost** [comment] 2017-03-03 23:22
In the future maybe some CI incorporating cross-browser testing would pick up these kinds of problems? Just a thought.

**Comment by itrestian** [comment] 2017-03-03 23:59
You mean version 1.16.0 crashes in your development environment but works in your production?

**Comment by jogold** [comment] 2017-03-04 07:29
Yes exactly. 

The webpack config is different in the two environments but I haven't found why it happens. Still investigating.

**Comment by tribou** [comment] 2017-03-06 04:55
I can confirm that 1.16.0 crashes the Chrome tab on OSX 10.11.6.  Safari and Firefox work fine.  For my project, this happens in both dev and prod build environments using webpack.

**Comment by pisaacs** [comment] 2017-03-07 03:51
Also confirming **Aw, Snap!** crashes when calling `authenticateUser`! 

Glad to have found this issue report (already wasted 5 hours trying to debug). Now I can stop thinking it's Chrome or a Chrome plugin or some other browser/Chrome profile issue.

An number of React packages use jsbn (from `npm list jsbn`):

```
└─┬ react-scripts@0.6.1
  ├─┬ fsevents@1.0.14
  │ └─┬ node-pre-gyp@0.6.29
  │   └─┬ request@2.73.0
  │     └─┬ http-signature@1.1.1
  │       └─┬ sshpk@1.8.3
  │         └── jsbn@0.1.0
  ├─┬ jest@15.1.1
  │ └─┬ jest-cli@15.1.1
  │   └─┬ jest-environment-jsdom@15.1.1
  │     └─┬ jsdom@9.5.0
  │       └─┬ request@2.75.0
  │         └─┬ http-signature@1.1.1
  │           └─┬ sshpk@1.10.0
  │             └── jsbn@0.1.0
  └─┬ webpack@1.13.2
    └─┬ watchpack@0.2.9
      └─┬ chokidar@1.6.0
        └─┬ fsevents@1.0.14
          └─┬ node-pre-gyp@0.6.29
            └─┬ request@2.73.0
              └─┬ http-signature@1.1.1
                └─┬ sshpk@1.8.3
                  └── jsbn@0.1.0
```

**Comment by gitjeff05** [comment] 2017-03-09 17:58
For what it's worth, this is *not* happening to me on v1.16.0
Chrome 56.0.2924.87 (64-bit)
Mac 10.11.6

Although, I just realized I'm still manually importing jsbn into my build configuration.

**Update**: Removed jsbn from my build (now that it is included in v1.16.0) and everything still works fine. I am using ember-cli -- which uses broccoli under the hood -- So no webpack here.

**Comment by element6** [comment] 2017-04-03 06:02
I was trying to see which line is crashing by changing the package.son file. Somehow the un-minified version didn't crash. 

I changed `"main": "dist/amazon-cognito-identity.min.js",` in node_modules/amazon-cognito-identity-js/package.json to `"main": "src/index.js",`

Unfortunately, it didn't crash. Maybe someone knows why minified version would cause this error.

**Comment by itrestian** [comment] 2017-04-03 20:35
Basically 1.16 pulled jsbn into our codebase which conflicts with react since it uses jsbn as well. 1.15 still uses the external jsbn version so it shouldn't conflict.

**Comment by itrestian** [comment] 2017-06-14 21:20
This should have been fixed by:

https://github.com/aws/amazon-cognito-identity-js/pull/294

**Closed as completed** 2017-06-14 21:22 UTC
