### ISSUE TITLE
 Error: Invalid login token. Couldn't verify signed token

### ISSUE THREAD

**Issue by ljovanovic** [aws/amazon-cognito-identity-js#91] opened 2016-07-28 22:20 UTC
My application login flow has been functioning fine for weeks and we are now receiving errors when we attempt to get AWS credentials with our cognito tokens.

{"__type":"NotAuthorizedException","message":"Invalid login token. Couldn't verify signed token."}

Has there been any changes in the APIs with a recent release?

**Comment by jbailey2010** [comment] 2016-07-28 22:39
Cognito User Pools went GA this afternoon, and what was supposed to be a seamless release has caused a few isolated incidents for which we're actively investigating the cause. Could you give me your user pool id so I can investigate further?

**Comment by dinomujki** [comment] 2016-07-28 22:52
Experiencing the same issue since the update.
+1

Update:
Issue persists even when new User Pools and Idenitity Pools are created.

**Comment by ljovanovic** [comment] 2016-07-28 22:56
My user pool is us-east-1_4M3fYzvqD

**Comment by jbailey2010** [comment] 2016-07-28 23:24
Hi guys,

Very sorry for the troubles. We've identified the issue causing the Cognito Federated Identities integration with User Pools to stop working on some clients. I'll update here when it's been resolved.

**Comment by jbailey2010** [comment] 2016-07-28 23:34
Can you guys try again? We believe we have resolved the issue.

**Comment by dinomujki** [comment] 2016-07-28 23:41
Yeah, works again for me. Thank you very much for being resolving it so promptly.

**Comment by jbailey2010** [comment] 2016-07-28 23:46
Excellent, happy to hear it! Sorry again for the troubles. If anyone else is having issues, comment here and we'll investigate further.

**Comment by tikipatel** [comment] 2016-07-28 23:46
It's back up!

**Comment by ljovanovic** [comment] 2016-07-28 23:48
Confirmed on my end as well.

**Comment by ljovanovic** [comment] 2016-07-28 23:49
@jbailey2010 do you me to leave this open or would you like me to close the issue?

**Comment by jbailey2010** [comment] 2016-07-29 00:03
If you guys aren't having issues, I'm happy to close.

**Closed as completed by jbailey2010** 2016-07-29 00:03 UTC

**Comment by nileshindexnine** [comment] 2017-06-29 06:03
i am also getting same error

**Comment by vaibhavAtbwellthy** [comment] 2017-10-10 08:42
Hey,
I am getting the same error now, This has been working fine for me all the time, Just since today, when i try to call this 
Method - cognitoCredentialsProvider.refresh(); to get the Congito Identity. 

Its is results in firing this exception - 
"com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Invalid login token. Couldn't verify signed token. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: a7db46b8-ad94-11e7-8418-c94b0b6898a1)"

Can anyone comment on this,
Please let me know if i am missing something here/ or want some more info from me.

Thanks.
